### ISSUE TITLE
Bluetooth socket error on android 11

### ISSUE THREAD

**Issue by Ffom** [inckie/AnotherGlass#2]
{"category":"BluetoothClient","context":{},"data":{},"exception":{"detailMessage":"read failed, socket might closed or timeout, read ret: -1","stackTrace":[{"declaringClass":"android.bluetooth.BluetoothSocket","fileName":"BluetoothSocket.java","lineNumber":758,"methodName":"readAll"},{"declaringClass":"android.bluetooth.BluetoothSocket","fileName":"BluetoothSocket.java","lineNumber":772,"methodName":"readInt"},{"declaringClass":"android.bluetooth.BluetoothSocket","fileName":"BluetoothSocket.java","lineNumber":404,"methodName":"connect"},{"declaringClass":"com.damn.anotherglass.core.BluetoothClient$Connection","fileName":"BluetoothClient.java","lineNumber":91,"methodName":"runLoop"},{"declaringClass":"com.damn.anotherglass.core.BluetoothClient$Connection","fileName":"BluetoothClient.java","lineNumber":59,"methodName":"run"}],"suppressedExceptions":[]},"level":4,"message":"Connection exception","subsystem":"BluetoothClient","timestamp":1657410875538}

I'm able to start the service for a second and then it quits

**Comment by inckie** [comment]
Fixed in updated UI
