### ISSUE TITLE
App won't build in android studio

### ISSUE THREAD

**Issue by glassuser** [inckie/AnotherGlass#3]
I get a glass gdk or xray-ui error!

**Comment by glassuser** [comment]
N

**Comment by glassuser** [comment]
What is Xray-ui, core and crash reporter? I can't find anything about them

**Comment by glassuser** [comment]
Ok, thanks. The GDK isn't in the macOS Android studio, I tried it in Windows and I was able to find it under 4.4 KitKat.

**Comment by inckie** [comment]
@glassuser its available for me on OSX with `Hide obsolete packages` flag off.
![Screenshot 2024-02-13 at 16 35 15](https://github.com/inckie/AnotherGlass/assets/24409942/55658668-74fb-429d-af07-965fe80698f8)

I've updated the project with x-ray fork, should be good to build now.

**Comment by glassuser** [comment]
Okay, I was able to build the glass apk, but the mobile build still results in an xray error. Is there something I should've done/downloaded?

**Comment by inckie** [comment]
@glassuser did you init/update git submodules?

**Comment by inckie** [comment]
@glassuser 
If you get thee x-ray error, I assume you did not init submodules (`AnotherGlass/externals/x-ray/` is empty).
Depending on your git version and OS, something like `git clone --recurse-submodules git@github.com:inckie/AnotherGlass.git` for clean clone, or 'submodule update --init' for existing.
Then you can open it in Android Studio and build.

**Comment by glassuser** [comment]
Ok, after trying this exact command, I get: 
fatal: clone of 'git@github.com:inckie/x-ray.git' into submodule path '/Users/mw/AnotherGlass/externals/x-ray' failed

**Comment by glassuser** [comment]
It also says: 
fatal: could not read from the remote repository

**Comment by inckie** [comment]
@glassuser its related to github ssh host keys configuration. Probably easier way to use some git GUI client then, since its hard to help there with github message exchange.

**Comment by inckie** [comment]
@glassuser ok, I need public fork, since repo was private at the time of forking, I'll re-create

**Comment by inckie** [comment]
@glassuser x-ray fork is now public, but probably you'll still see ssh keys issues under Windows (requires some git configuration that can be googled)

**Comment by glassuser** [comment]
Thank You!!!! It works!
